# config.py

TELEGRAM_TOKEN = "7856358847:AAE3t_G9S5UXO1_I88uo1d88jMW7NRhQMx4"
CHAT_ID = "-1002667517368"

SYMBOLS = [
    "BTCUSDT", "ETHUSDT", "SOLUSDT", "AVAXUSDT", "INJUSDT", "LINKUSDT", "NEARUSDT",
    "ARBUSDT", "ADAUSDT", "ATOMUSDT", "DOTUSDT", "OPUSDT", "SUIUSDT", "APTUSDT",
    "MATICUSDT", "TIAUSDT", "PYTHUSDT", "PEPEUSDT", "DOGEUSDT", "SHIBUSDT",
    "RUNEUSDT", "FETUSDT", "RNDRUSDT", "JASMYUSDT", "1000SATSUSDT", "STXUSDT",
    "BLURUSDT", "DYDXUSDT", "GALAUSDT", "LTCUSDT", "TRXUSDT", "AAVEUSDT",
    "ARDRUSDT", "PAXGUSDT", "SEIUSDT", "COTIUSDT", "LDOUSDT", "CFXUSDT",
    "WIFUSDT", "BICOUSDT", "IDUSDT", "CVCUSDT", "AGIXUSDT", "NKNUSDT",
    "OCEANUSDT", "HIGHUSDT", "MAGICUSDT", "HOOKUSDT", "VELODROMEUSDT"
]

TIMEFRAME = "4h"
ROUND_TIME_MINUTES = 240
FOLLOW_UP_MINUTES = 120
